/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import data.Brand;
import data.Model;
import data.Phases;
import data.Tools;
import data.UserSystem;
import db.DBHandleData;
import db.DBInitData;
import javax.swing.JOptionPane;

/**
 *
 * @author tanzil
 */
public class AddCar extends javax.swing.JDialog {

    /**
     * Creates new form AddCar
     */
    UserSystem user;
    CreateReceiveInvoice parent;
    CreateSaleInvoice parent1;
    int check;

    public AddCar(java.awt.Dialog parent, boolean modal, int i, UserSystem user) {

        super(parent, modal);

        Tools.LookAndFeel();
        System.out.println(parent);
        this.user = user;
        check = i;
        if (i == 1) {
            this.parent1 = (CreateSaleInvoice) parent;
            System.out.println("createsaleinvoice");
        } else if (i == 2) {
            this.parent = (CreateReceiveInvoice) parent;
            System.out.println("createreceiveinvoice");
        } else {
            parent = null;
        }
        initComponents();
        this.setLocationRelativeTo(null);
        DBInitData.initHangxe(cbbHangsx);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        lblTenxe = new javax.swing.JLabel();
        txtTenxe = new javax.swing.JTextField();
        lblModel = new javax.swing.JLabel();
        lblHangsx = new javax.swing.JLabel();
        cbbModel = new javax.swing.JComboBox();
        cbbHangsx = new javax.swing.JComboBox();
        btnReset = new javax.swing.JButton();
        btnThemmoi = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add New Car");

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Car Information", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 18), new java.awt.Color(255, 51, 0))); // NOI18N

        lblTenxe.setText("Car's Name:");

        lblModel.setText("Model: ");

        lblHangsx.setText("Brand:");

        cbbModel.setEditable(true);

        cbbHangsx.setEditable(true);
        cbbHangsx.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbbHangsxItemStateChanged(evt);
            }
        });

        btnReset.setForeground(new java.awt.Color(0, 153, 0));
        btnReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Yellow Ball.png"))); // NOI18N
        btnReset.setText("RESET");
        btnReset.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnReset.setHideActionText(true);
        btnReset.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnThemmoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Add Green Button.png"))); // NOI18N
        btnThemmoi.setText("ADD");
        btnThemmoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemmoiActionPerformed(evt);
            }
        });

        btnCancel.setBackground(new java.awt.Color(255, 255, 255));
        btnCancel.setForeground(new java.awt.Color(255, 0, 0));
        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Cancel Red Button.png"))); // NOI18N
        btnCancel.setText("CANCEL");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(btnReset)
                        .addGap(18, 18, 18)
                        .addComponent(btnThemmoi)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancel))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(lblHangsx, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbbHangsx, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblModel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTenxe, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTenxe)
                            .addComponent(cbbModel, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHangsx, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbbHangsx, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblModel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbbModel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTenxe, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTenxe, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(btnThemmoi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnReset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 414, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        cbbHangsx.setSelectedIndex(0);
        cbbModel.setSelectedIndex(0);
        txtTenxe.setText("");
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnThemmoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemmoiActionPerformed
        // TODO add your handling code here:
        Brand hsx = (Brand) cbbHangsx.getSelectedItem();
        Model m = (Model) cbbModel.getSelectedItem();
        String sql = "INSERT Car (IDModel,CarName,Status) VALUES (?, ?,0)";
        if (txtTenxe.getText().equals("") || cbbHangsx.getSelectedIndex() == 0 || cbbModel.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, Phases.ERROR_EMPTY_FIELD, Phases.ERROR_MESSAGE, JOptionPane.ERROR_MESSAGE);
        } else {

            String[] d = {Integer.toString(m.IdBrand), txtTenxe.getText()};
            if (DBHandleData.CheckForInsert("SELECT CarName FROM Car", txtTenxe.getText())) {
                JOptionPane.showMessageDialog(this, Phases.ADD_ERROR_EXIST, Phases.ERROR_MESSAGE, JOptionPane.ERROR_MESSAGE);
            } else {
                int rows = db.DBHandleData.UpdateData(sql, d);
                if (rows > 0) {
                    JOptionPane.showMessageDialog(this, Phases.ADD_SUCCESSFULL);
                } else {
                    JOptionPane.showMessageDialog(this, Phases.ADD_FAILURE, Phases.ERROR_MESSAGE, JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_btnThemmoiActionPerformed

    private void cbbHangsxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbbHangsxItemStateChanged
        // TODO add your handling code here:
        if (evt.getStateChange() == evt.SELECTED) {
            Brand hsx = (Brand) cbbHangsx.getSelectedItem();
            String sql = "SELECT * FROM Model WHERE IDBrand = " + hsx.Id;
            DBInitData.initModel(cbbModel, sql);
        }

    }//GEN-LAST:event_cbbHangsxItemStateChanged

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        if (check == 1) {
            if (txtTenxe.getText().equals("")) {
                this.dispose();
            } else {
                int c = JOptionPane.showConfirmDialog(this, Phases.QUESTION_SELL_CAR, Phases.WARNING_MESSAGE, JOptionPane.OK_CANCEL_OPTION);
                if (c == JOptionPane.OK_OPTION) {
                    new CreateReceiveInvoice(null, true, user, txtTenxe.getText()).setVisible(true);
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(this, Phases.ERROR_SELL_CAR,Phases.INFORMATION_MESSAGE,JOptionPane.WARNING_MESSAGE);
                    this.dispose();
                }
                
            }
        } else if (check == 2) {
            if (txtTenxe.getText().equals("")) {
                this.dispose();
            } else {
                parent.EvtVehicleName(txtTenxe.getText());
                this.dispose();
            }
        } else {
            this.dispose();
        }

    }//GEN-LAST:event_btnCancelActionPerformed
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnThemmoi;
    private javax.swing.JComboBox cbbHangsx;
    private javax.swing.JComboBox cbbModel;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lblHangsx;
    private javax.swing.JLabel lblModel;
    private javax.swing.JLabel lblTenxe;
    private javax.swing.JTextField txtTenxe;
    // End of variables declaration//GEN-END:variables
}
