/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import data.Phases;
import data.Tools;
import db.DBHandleData;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author tanzil
 */
public class AddSupplier extends javax.swing.JDialog {

    /**
     * Creates new form AddSupplier
     */
    CreateReceiveInvoice parent;

    public AddSupplier(java.awt.Dialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        Tools.LookAndFeel();
        this.setLocationRelativeTo(null);
        this.parent = (CreateReceiveInvoice) parent;
    }

    public void Reset() {
        txtAdd.setText("");
        txtPhone.setText("");
        txtName.setText("");
        txtEmailSupp.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        lblName = new javax.swing.JLabel();
        lblAdd = new javax.swing.JLabel();
        txtAdd = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        lblEmailSupp = new javax.swing.JLabel();
        txtEmailSupp = new javax.swing.JTextField();
        lblTenkh5 = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        btnAddSupp = new javax.swing.JButton();
        btnResetSupp = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add New Supplier");

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Add New Supplier", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 18), java.awt.Color.black)); // NOI18N

        lblName.setText("Name:");

        lblAdd.setText("Address:");

        lblEmailSupp.setText("Email:");

        lblTenkh5.setText("Phone:");

        btnAddSupp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        btnAddSupp.setText("Add");
        btnAddSupp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddSuppActionPerformed(evt);
            }
        });

        btnResetSupp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Yellow Ball.png"))); // NOI18N
        btnResetSupp.setText("Reset");
        btnResetSupp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetSuppActionPerformed(evt);
            }
        });

        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Cancel Red Button.png"))); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblEmailSupp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblName, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                            .addComponent(lblTenkh5, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                            .addComponent(lblAdd, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtName, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                            .addComponent(txtAdd)
                            .addComponent(txtPhone)
                            .addComponent(txtEmailSupp)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAddSupp, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(btnResetSupp, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCancel)))
                .addContainerGap())
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAddSupp, btnCancel, btnResetSupp});

        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTenkh5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEmailSupp, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmailSupp, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddSupp, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnResetSupp, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddSuppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddSuppActionPerformed
        // TODO add your handling code here:
        Pattern p = Pattern.compile("0[0-9]{9,10}");
        Matcher matcher = p.matcher(txtPhone.getText());
        Pattern pp = Pattern.compile("[a-zA-Z_]+[0-9]*@[a-zA-Z]{3,15}.[a-zA-Z]{3,15}[.[a-zA-Z]{3,15}]*");
        Matcher m = pp.matcher(txtEmailSupp.getText());

        if (txtName.getText().equals("") || txtAdd.getText().equals("")) {
            JOptionPane.showMessageDialog(this,Phases.ERROR_EMPTY_FIELD, Phases.ERROR_MESSAGE, JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (!matcher.matches()) {
            JOptionPane.showMessageDialog(this, Phases.INVALID_FORMAT, Phases.ERROR_MESSAGE, JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (!m.matches()) {
            JOptionPane.showMessageDialog(this, Phases.INVALID_FORMAT, Phases.ERROR_MESSAGE, JOptionPane.ERROR_MESSAGE);
            return;
        }
        String sql = "INSERT Supplier VALUES (?,?,?,?)";
        String[] data = {txtName.getText(), txtAdd.getText(), txtPhone.getText(), txtEmailSupp.getText()};
        if (DBHandleData.CheckForInsert("SELECT SuppName FROM Supplier", txtName.getText())) {
            JOptionPane.showMessageDialog(this, Phases.ADD_SUPPLIER_EXIST, Phases.ERROR_MESSAGE, JOptionPane.ERROR_MESSAGE);
        } else {
            int rows = db.DBHandleData.UpdateData(sql, data);
            if (rows > 0) {
                JOptionPane.showMessageDialog(this,Phases.ADD_SUCCESSFULL);
            } else {
                JOptionPane.showMessageDialog(this, Phases.ADD_FAILURE);
            }
        }
    }//GEN-LAST:event_btnAddSuppActionPerformed

    private void btnResetSuppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetSuppActionPerformed
        // TODO add your handling code here:
        Reset();
    }//GEN-LAST:event_btnResetSuppActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        if (txtName.getText().equals("")) {
            this.dispose();
        } else {
            parent.EvtSuppName(txtName.getText());
            this.dispose();
        }

    }//GEN-LAST:event_btnCancelActionPerformed
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddSupp;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnResetSupp;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblAdd;
    private javax.swing.JLabel lblEmailSupp;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblTenkh5;
    private javax.swing.JTextField txtAdd;
    private javax.swing.JTextField txtEmailSupp;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhone;
    // End of variables declaration//GEN-END:variables
}
