/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import data.Tools;
import data.UserSystem;
import javax.swing.*;

/**
 *
 * @author tanzil
 */
public class ManageSystem extends JFrame {

    /**
     * Creates new form ManageSystem
     */
    UserSystem user;

    public ManageSystem(UserSystem user) {
        initComponents();
        Tools.LookAndFeel();
        this.setLocationRelativeTo(null);
        this.setTitle("EXCISE AND TAXATION MMANAGEMENT");
        this.user = user;

        if (user.getMaqt() == 2) {
            mnDeleteCar.setEnabled(false);
            mnAddAcc.setEnabled(false);
            mnReport.setEnabled(false);
            mnUpdateAcc.setEnabled(false);
        }
        if (user.getMaqt() == 1) {
            mnCreateASales.setEnabled(false);
            mnCreateAbill.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnFile = new javax.swing.JMenu();
        mnLogout = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnExit = new javax.swing.JMenuItem();
        mnCar = new javax.swing.JMenu();
        mnAddCar = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        mnSearchCar = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        mnRegisterCar = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        mnDeleteCar = new javax.swing.JMenuItem();
        mnSales = new javax.swing.JMenu();
        mnCreateAbill = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        mnCreateASales = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        mnSearchSales = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mnCusDebt = new javax.swing.JMenuItem();
        jSeparator8 = new javax.swing.JPopupMenu.Separator();
        mnReport = new javax.swing.JMenuItem();
        mnCustomer = new javax.swing.JMenu();
        mnAddcustomer = new javax.swing.JMenuItem();
        jSeparator9 = new javax.swing.JPopupMenu.Separator();
        mnSearchCustomer = new javax.swing.JMenuItem();
        jSeparator10 = new javax.swing.JPopupMenu.Separator();
        mnUpdateCustomer = new javax.swing.JMenuItem();
        mnuAccount = new javax.swing.JMenu();
        mnAddAcc = new javax.swing.JMenuItem();
        jSeparator11 = new javax.swing.JPopupMenu.Separator();
        mnUpdateAcc = new javax.swing.JMenuItem();
        space = new javax.swing.JPopupMenu.Separator();
        mnChangePass = new javax.swing.JMenuItem();
        jSeparator12 = new javax.swing.JPopupMenu.Separator();
        mnEditInfo = new javax.swing.JMenuItem();
        mnAbout = new javax.swing.JMenu();
        mnuAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Manage Vehicle");
        setResizable(false);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/CarBanner.jpg"))); // NOI18N

        jMenuBar1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jMenuBar1.setForeground(new java.awt.Color(255, 255, 255));
        jMenuBar1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        mnFile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Run.png"))); // NOI18N
        mnFile.setText("File");
        mnFile.setActionCommand("&File");

        mnLogout.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.ALT_MASK));
        mnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Red Ball.png"))); // NOI18N
        mnLogout.setText("LogOut");
        mnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnLogoutActionPerformed(evt);
            }
        });
        mnFile.add(mnLogout);
        mnFile.add(jSeparator1);

        mnExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        mnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Eject Blue Button.png"))); // NOI18N
        mnExit.setText("Exit");
        mnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnExitActionPerformed(evt);
            }
        });
        mnFile.add(mnExit);

        jMenuBar1.add(mnFile);

        mnCar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Add Green Button.png"))); // NOI18N
        mnCar.setText("Vehilce");

        mnAddCar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        mnAddCar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Add.png"))); // NOI18N
        mnAddCar.setText("Add New Vehicle");
        mnAddCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnAddCarActionPerformed(evt);
            }
        });
        mnCar.add(mnAddCar);
        mnCar.add(jSeparator3);

        mnSearchCar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        mnSearchCar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Spotlight Blue Button.png"))); // NOI18N
        mnSearchCar.setText("Search Vehicle");
        mnSearchCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnSearchCarActionPerformed(evt);
            }
        });
        mnCar.add(mnSearchCar);
        mnCar.add(jSeparator4);

        mnRegisterCar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        mnRegisterCar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Write Document.png"))); // NOI18N
        mnRegisterCar.setText("Register Data Vehicle");
        mnRegisterCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnRegisterCarActionPerformed(evt);
            }
        });
        mnCar.add(mnRegisterCar);
        mnCar.add(jSeparator5);

        mnDeleteCar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_DELETE, java.awt.event.InputEvent.CTRL_MASK));
        mnDeleteCar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Minus Red Button.png"))); // NOI18N
        mnDeleteCar.setText("Delete Vehicle");
        mnDeleteCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnDeleteCarActionPerformed(evt);
            }
        });
        mnCar.add(mnDeleteCar);

        jMenuBar1.add(mnCar);

        mnSales.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Donate.png"))); // NOI18N
        mnSales.setText("Invoice");

        mnCreateAbill.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_MASK));
        mnCreateAbill.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Green Ball.png"))); // NOI18N
        mnCreateAbill.setText("Create Receive Invoice");
        mnCreateAbill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnCreateAbillActionPerformed(evt);
            }
        });
        mnSales.add(mnCreateAbill);
        mnSales.add(jSeparator6);

        mnCreateASales.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_MASK));
        mnCreateASales.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Blue Ball.png"))); // NOI18N
        mnCreateASales.setText("Create Sale Invoice");
        mnCreateASales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnCreateASalesActionPerformed(evt);
            }
        });
        mnSales.add(mnCreateASales);
        mnSales.add(jSeparator7);

        mnSearchSales.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.SHIFT_MASK));
        mnSearchSales.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Spotlight Blue Button.png"))); // NOI18N
        mnSearchSales.setText("Search Invoice");
        mnSearchSales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnSearchSalesActionPerformed(evt);
            }
        });
        mnSales.add(mnSearchSales);
        mnSales.add(jSeparator2);

        mnCusDebt.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.SHIFT_MASK));
        mnCusDebt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Coherence.png"))); // NOI18N
        mnCusDebt.setText("View Customer's Debt");
        mnCusDebt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnCusDebtActionPerformed(evt);
            }
        });
        mnSales.add(mnCusDebt);
        mnSales.add(jSeparator8);

        mnReport.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.SHIFT_MASK));
        mnReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Export To Document.png"))); // NOI18N
        mnReport.setText("Report");
        mnReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnReportActionPerformed(evt);
            }
        });
        mnSales.add(mnReport);

        jMenuBar1.add(mnSales);

        mnCustomer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Users.png"))); // NOI18N
        mnCustomer.setText("Customer");

        mnAddcustomer.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        mnAddcustomer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Add.png"))); // NOI18N
        mnAddcustomer.setText("Add New Customer");
        mnAddcustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnAddcustomerActionPerformed(evt);
            }
        });
        mnCustomer.add(mnAddcustomer);
        mnCustomer.add(jSeparator9);

        mnSearchCustomer.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        mnSearchCustomer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Spotlight Blue Button.png"))); // NOI18N
        mnSearchCustomer.setText("Search Customer");
        mnSearchCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnSearchCustomerActionPerformed(evt);
            }
        });
        mnCustomer.add(mnSearchCustomer);
        mnCustomer.add(jSeparator10);

        mnUpdateCustomer.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        mnUpdateCustomer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Write Document.png"))); // NOI18N
        mnUpdateCustomer.setText("Update Customer");
        mnUpdateCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnUpdateCustomerActionPerformed(evt);
            }
        });
        mnCustomer.add(mnUpdateCustomer);

        jMenuBar1.add(mnCustomer);

        mnuAccount.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/User.png"))); // NOI18N
        mnuAccount.setText("Account");

        mnAddAcc.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.SHIFT_MASK));
        mnAddAcc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Add.png"))); // NOI18N
        mnAddAcc.setText("Add New Account");
        mnAddAcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnAddAccActionPerformed(evt);
            }
        });
        mnuAccount.add(mnAddAcc);
        mnuAccount.add(jSeparator11);

        mnUpdateAcc.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.SHIFT_MASK));
        mnUpdateAcc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Write Document.png"))); // NOI18N
        mnUpdateAcc.setText("Update Account");
        mnUpdateAcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnUpdateAccActionPerformed(evt);
            }
        });
        mnuAccount.add(mnUpdateAcc);
        mnuAccount.add(space);

        mnChangePass.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_MASK));
        mnChangePass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Plugin Green Button.png"))); // NOI18N
        mnChangePass.setText("Change Password");
        mnChangePass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnChangePassActionPerformed(evt);
            }
        });
        mnuAccount.add(mnChangePass);
        mnuAccount.add(jSeparator12);

        mnEditInfo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.SHIFT_MASK));
        mnEditInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Menu Item.png"))); // NOI18N
        mnEditInfo.setText("Edit Infomation");
        mnEditInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnEditInfoActionPerformed(evt);
            }
        });
        mnuAccount.add(mnEditInfo);

        jMenuBar1.add(mnuAccount);

        mnAbout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Help Blue Button.png"))); // NOI18N
        mnAbout.setText("Help");

        mnuAbout.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        mnuAbout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Get Info Purple Button.png"))); // NOI18N
        mnuAbout.setText("About Us");
        mnuAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAboutActionPerformed(evt);
            }
        });
        mnAbout.add(mnuAbout);

        jMenuBar1.add(mnAbout);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnExitActionPerformed
        // TODO add your handling code here:
        this.dispose();
        System.exit(0);
    }//GEN-LAST:event_mnExitActionPerformed

    private void mnAddCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnAddCarActionPerformed
        // TODO add your handling code here:
        new AddCar(null, true, 0, user).setVisible(true);
    }//GEN-LAST:event_mnAddCarActionPerformed

    private void mnSearchCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnSearchCarActionPerformed
        // TODO add your handling code here:
        new SearchCar(this, true, user).setVisible(true);
    }//GEN-LAST:event_mnSearchCarActionPerformed

    private void mnRegisterCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnRegisterCarActionPerformed
        // TODO add your handling code here:
        new RegisterCar(this, true).setVisible(true);
    }//GEN-LAST:event_mnRegisterCarActionPerformed

    private void mnDeleteCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnDeleteCarActionPerformed
        // TODO add your handling code here:
        new DeleteCar(this, true).setVisible(true);
    }//GEN-LAST:event_mnDeleteCarActionPerformed

    private void mnSearchCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnSearchCustomerActionPerformed
        // TODO add your handling code here:
        new SearchCustomer(this, true, user).setVisible(true);
    }//GEN-LAST:event_mnSearchCustomerActionPerformed

    private void mnAddcustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnAddcustomerActionPerformed
        // TODO add your handling code here:
        new AddCustomer(null, true, user).setVisible(true);
    }//GEN-LAST:event_mnAddcustomerActionPerformed

    private void mnUpdateCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnUpdateCustomerActionPerformed
        // TODO add your handling code here:
        new UpdateCustomer(this, true, user).setVisible(true);
    }//GEN-LAST:event_mnUpdateCustomerActionPerformed

    private void mnuAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAboutActionPerformed
        // TODO add your handling code here:
        new About(this, true).setVisible(true);
    }//GEN-LAST:event_mnuAboutActionPerformed

    private void mnCreateAbillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnCreateAbillActionPerformed
        // TODO add your handling code here:
        new CreateReceiveInvoice(null, true, user, "").setVisible(true);
    }//GEN-LAST:event_mnCreateAbillActionPerformed

    private void mnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnLogoutActionPerformed
        // TODO add your handling code here:
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mnLogoutActionPerformed

    private void mnSearchSalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnSearchSalesActionPerformed
        // TODO add your handling code here:new 
        new SearchSales(this, true).setVisible(true);
    }//GEN-LAST:event_mnSearchSalesActionPerformed

    private void mnAddAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnAddAccActionPerformed
        // TODO add your handling code here:
        new AddAccount(this, true).setVisible(true);
    }//GEN-LAST:event_mnAddAccActionPerformed

    private void mnChangePassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnChangePassActionPerformed
        // TODO add your handling code here:
        new ChangePassword(this, true, user).setVisible(true);
    }//GEN-LAST:event_mnChangePassActionPerformed

    private void mnEditInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnEditInfoActionPerformed
        // TODO add your handling code here:UP
        new EditAccount(null, true, user).setVisible(true);
    }//GEN-LAST:event_mnEditInfoActionPerformed

    private void mnUpdateAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnUpdateAccActionPerformed
        // TODO add your handling code here:
        new UpdateAccount(this, true, user).setVisible(true);
    }//GEN-LAST:event_mnUpdateAccActionPerformed

    private void mnCreateASalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnCreateASalesActionPerformed
        // TODO add your handling code here:
        new CreateSaleInvoice(this, true, user).setVisible(true);
    }//GEN-LAST:event_mnCreateASalesActionPerformed

    private void mnReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnReportActionPerformed
        // TODO add your handling code here:
        new Report(this, true).setVisible(true);
    }//GEN-LAST:event_mnReportActionPerformed

    private void mnCusDebtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnCusDebtActionPerformed
        // TODO add your handling code here:
        new ViewCusDebt(this, true).setVisible(true);
    }//GEN-LAST:event_mnCusDebtActionPerformed
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator10;
    private javax.swing.JPopupMenu.Separator jSeparator11;
    private javax.swing.JPopupMenu.Separator jSeparator12;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JPopupMenu.Separator jSeparator8;
    private javax.swing.JPopupMenu.Separator jSeparator9;
    private javax.swing.JMenu mnAbout;
    private javax.swing.JMenuItem mnAddAcc;
    private javax.swing.JMenuItem mnAddCar;
    private javax.swing.JMenuItem mnAddcustomer;
    private javax.swing.JMenu mnCar;
    private javax.swing.JMenuItem mnChangePass;
    private javax.swing.JMenuItem mnCreateASales;
    private javax.swing.JMenuItem mnCreateAbill;
    private javax.swing.JMenuItem mnCusDebt;
    private javax.swing.JMenu mnCustomer;
    private javax.swing.JMenuItem mnDeleteCar;
    private javax.swing.JMenuItem mnEditInfo;
    private javax.swing.JMenuItem mnExit;
    private javax.swing.JMenu mnFile;
    private javax.swing.JMenuItem mnLogout;
    private javax.swing.JMenuItem mnRegisterCar;
    private javax.swing.JMenuItem mnReport;
    private javax.swing.JMenu mnSales;
    private javax.swing.JMenuItem mnSearchCar;
    private javax.swing.JMenuItem mnSearchCustomer;
    private javax.swing.JMenuItem mnSearchSales;
    private javax.swing.JMenuItem mnUpdateAcc;
    private javax.swing.JMenuItem mnUpdateCustomer;
    private javax.swing.JMenuItem mnuAbout;
    private javax.swing.JMenu mnuAccount;
    private javax.swing.JPopupMenu.Separator space;
    // End of variables declaration//GEN-END:variables
}
