/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import data.MyImages;
import data.Phases;
import data.Tools;
import db.DBHandleData;
import java.io.File;
import java.io.IOException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author tanzil
 */
public class Register extends javax.swing.JDialog {

    /**
     * Creates new form Register
     */
    RegisterCar parent;
    CreateReceiveInvoice parent1;
    int Maxe;
    int check;

    public Register(java.awt.Dialog parent, boolean modal, Vector v, int i) {
        super(parent, modal);
        Tools.LookAndFeel();
        initComponents();
        this.setLocationRelativeTo(null);
        check = i;
        if (i == 1) {
            this.parent1 = (CreateReceiveInvoice) parent;
        } else if (i == 2) {
            this.parent = (RegisterCar) parent;
        }

        setData(v);
    }

    public void Reset() {
        link = new String[4];
        lblAnh1.setIcon(null);
        lblAnh2.setIcon(null);
        lblAnh3.setIcon(null);
        lblAnh4.setIcon(null);
        lblAnh1.setText("No Images");
        lblAnh2.setText("No Images");
        lblAnh3.setText("No Images");
        lblAnh4.setText("No Images");
        txtChieucao.setText("");
        txtChieudai.setText("");
        txtChieurong.setText("");
        txtCongsuatmax.setText("");
        txtDongco.setText("");
        txtHopso.setText("");
        txtKieudc.setText("");
        txtMaxspeed.setText("");
        txtNamsx.setText("");
        txtNhienlieu.setText("");
        txtSoghe.setText("");
        txtTrongluong.setText("");
    }

    public void setData(Vector v) {
        lblTxe.setText(v.get(1).toString().trim());
        lblThang.setText(v.get(2).toString().trim());
        lblTModel.setText(v.get(3).toString().trim());
        Maxe = Integer.parseInt(v.get(0).toString().trim());
        if (v.get(5) != null) {
            Tools.fitImageToLabel(lblAnh1, v.get(5).toString().trim());
        } else {
            lblAnh1.setText("No Images");
        }
        if (v.get(6) != null) {
            Tools.fitImageToLabel(lblAnh2, v.get(6).toString().trim());
        } else {
            lblAnh2.setText("No Images");
        }
        if (v.get(7) != null) {
            Tools.fitImageToLabel(lblAnh3, v.get(7).toString().trim());
        } else {
            lblAnh3.setText("No Images");
        }
        if (v.get(8) != null) {
            Tools.fitImageToLabel(lblAnh4, v.get(8).toString().trim());
        } else {
            lblAnh4.setText("No Images");
        }
        if (v.get(10) != null) {
            txtDongco.setText(v.get(10).toString().trim());
        }
        if (v.get(11) != null) {
            txtKieudc.setText(v.get(11).toString().trim());
        }
        if (v.get(12) != null) {
            txtNhienlieu.setText(v.get(12).toString().trim());
        }
        if (v.get(13) != null) {
            txtHopso.setText(v.get(13).toString().trim());
        }
        if (v.get(14) != null) {
            txtCongsuatmax.setText(v.get(14).toString().trim());
        }
        if (v.get(15) != null) {
            txtMaxspeed.setText(v.get(15).toString().trim());
        }
        if (v.get(16) != null) {
            txtChieudai.setText(v.get(16).toString().trim());
        }
        if (v.get(18) != null) {
            txtChieucao.setText(v.get(18).toString().trim());
        }
        if (v.get(17) != null) {
            txtChieurong.setText(v.get(17).toString().trim());
        }
        if (v.get(20) != null) {
            txtSoghe.setText(v.get(20).toString().trim());
        }
        if (v.get(9) != null) {
            txtNamsx.setText(v.get(9).toString().trim());
        }
        if (v.get(19) != null) {
            txtTrongluong.setText(v.get(19).toString().trim());

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        lblNamsx = new javax.swing.JLabel();
        txtNamsx = new javax.swing.JTextField();
        lblMaxspeed = new javax.swing.JLabel();
        txtMaxspeed = new javax.swing.JTextField();
        txtChieudai = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtDongco = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtChieurong = new javax.swing.JTextField();
        lblChieurong = new javax.swing.JLabel();
        txtKieudc = new javax.swing.JTextField();
        lblKieudc = new javax.swing.JLabel();
        txtChieucao = new javax.swing.JTextField();
        lblChieucao = new javax.swing.JLabel();
        txtNhienlieu = new javax.swing.JTextField();
        lblNhienlieu = new javax.swing.JLabel();
        txtTrongluong = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtHopso = new javax.swing.JTextField();
        lblHopso = new javax.swing.JLabel();
        txtSoghe = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtCongsuatmax = new javax.swing.JTextField();
        lblMaxcongsuat = new javax.swing.JLabel();
        btnSubmit = new javax.swing.JButton();
        btnRs = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblAnh1 = new javax.swing.JLabel();
        lblAnh2 = new javax.swing.JLabel();
        lblAnh3 = new javax.swing.JLabel();
        lblAnh4 = new javax.swing.JLabel();
        btnSelect = new javax.swing.JButton();
        btnSelect2 = new javax.swing.JButton();
        btnSelect3 = new javax.swing.JButton();
        btnSelect1 = new javax.swing.JButton();
        lblTenxe = new javax.swing.JLabel();
        lblTxe = new javax.swing.JLabel();
        lblTenhang = new javax.swing.JLabel();
        lblThang = new javax.swing.JLabel();
        lblTenmodel = new javax.swing.JLabel();
        lblTModel = new javax.swing.JLabel();
        btnUpload = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Imformation");

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Detail Infomation", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 18))); // NOI18N

        lblNamsx.setText("Product Year:");

        lblMaxspeed.setText("Maximum Speed:");

        jLabel4.setText("Length:");

        jLabel5.setText("Engine:");

        lblChieurong.setText("Width:");

        lblKieudc.setText("Engine Type:");

        lblChieucao.setText("Heigh:");

        lblNhienlieu.setText("Fuel:");

        jLabel10.setText("Weight:");

        lblHopso.setText("Tranmission:");

        jLabel12.setText("Num of Seat:");

        lblMaxcongsuat.setText("Maximum Capacity:");

        btnSubmit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Clear Green Button.png"))); // NOI18N
        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        btnRs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Yellow Ball.png"))); // NOI18N
        btnRs.setText("Reset");
        btnRs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRsActionPerformed(evt);
            }
        });

        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Cancel Red Button.png"))); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAnh1.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        lblAnh1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAnh1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(lblAnh1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 130));

        lblAnh2.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        lblAnh2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAnh2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(lblAnh2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 220, 130));

        lblAnh3.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        lblAnh3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAnh3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(lblAnh3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 230, 120));

        lblAnh4.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        lblAnh4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAnh4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(lblAnh4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, 220, 120));

        btnSelect.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Import Picture Document.png"))); // NOI18N
        btnSelect.setText("Select");
        btnSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectActionPerformed(evt);
            }
        });
        jPanel1.add(btnSelect, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, -1));

        btnSelect2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Import Picture Document.png"))); // NOI18N
        btnSelect2.setText("Select");
        btnSelect2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelect2ActionPerformed(evt);
            }
        });
        jPanel1.add(btnSelect2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, 100, -1));

        btnSelect3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Import Picture Document.png"))); // NOI18N
        btnSelect3.setText("Select");
        btnSelect3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelect3ActionPerformed(evt);
            }
        });
        jPanel1.add(btnSelect3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 320, 100, -1));

        btnSelect1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Import Picture Document.png"))); // NOI18N
        btnSelect1.setText("Select");
        btnSelect1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelect1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnSelect1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, 100, -1));

        lblTenxe.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        lblTenxe.setText("Name:");

        lblTxe.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        lblTxe.setForeground(new java.awt.Color(255, 0, 0));

        lblTenhang.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        lblTenhang.setText("Brand:");

        lblThang.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        lblThang.setForeground(new java.awt.Color(255, 0, 0));

        lblTenmodel.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        lblTenmodel.setText("Model: ");

        lblTModel.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        lblTModel.setForeground(new java.awt.Color(255, 0, 0));

        btnUpload.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Send Document.png"))); // NOI18N
        btnUpload.setText("Upload");
        btnUpload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUploadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblTenxe, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblChieucao, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblNamsx, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblKieudc, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblNhienlieu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(lblMaxspeed, javax.swing.GroupLayout.PREFERRED_SIZE, 92, Short.MAX_VALUE)
                                        .addComponent(lblChieurong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblHopso, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtMaxspeed, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                            .addComponent(txtChieurong, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtChieudai, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtTrongluong, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtNhienlieu, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtDongco, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtNamsx, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtChieucao, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtKieudc)
                            .addComponent(txtSoghe, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtHopso, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblTxe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(lblMaxcongsuat, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCongsuatmax)))
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(lblTenhang, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblThang, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(77, 77, 77)
                                .addComponent(lblTenmodel, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblTModel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(225, 225, 225)
                        .addComponent(btnUpload)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSubmit)
                .addGap(31, 31, 31)
                .addComponent(btnRs)
                .addGap(30, 30, 30)
                .addComponent(btnCancel)
                .addGap(64, 64, 64))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTModel, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblTenxe, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblTxe, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblTenhang, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblThang, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblTenmodel, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMaxspeed, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMaxspeed))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtChieudai))
                        .addGap(11, 11, 11)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblChieurong, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtChieurong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblChieucao, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtChieucao))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNamsx, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNamsx))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDongco))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblKieudc, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtKieudc))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNhienlieu, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNhienlieu))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblHopso)
                            .addComponent(txtHopso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(txtSoghe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtTrongluong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUpload)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSubmit)
                            .addComponent(btnRs, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCongsuatmax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMaxcongsuat))
                        .addGap(81, 81, 81))))
        );

        jPanel7Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnCancel, btnRs, btnSubmit});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 818, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        if (check == 1) {
            this.dispose();
        } else if (check == 2) {
            parent.Search();
            this.dispose();
        }
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnRsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRsActionPerformed
        // TODO add your handling code here:
        Reset();
    }//GEN-LAST:event_btnRsActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        Pattern p = Pattern.compile("\\d+");
        Matcher m = p.matcher(txtNamsx.getText());
        Matcher m2 = p.matcher(txtMaxspeed.getText());
        Matcher m3 = p.matcher(txtChieudai.getText());
        Matcher m4 = p.matcher(txtChieurong.getText());
        Matcher m5 = p.matcher(txtChieucao.getText());
        Matcher m6 = p.matcher(txtTrongluong.getText());
        Matcher m7 = p.matcher(txtSoghe.getText());
        src = "images";
        String sql = "UPDATE Car SET Picture1 = ?, Picture2 = ?, Picture3 = ?, Picture4 = ?, "
                + "YearCar = ?, Engine = ?, EngineType = ?, Fuel = ?, Tranmission = ?, "
                + "MaxCapacity = ?, MaxSpeed = ?, Length = ?, Width = ?, "
                + "Height = ?, Weight = ?, Numberseat = ? "
                + "WHERE IDCar= " + Maxe;
        // Printing the sql command to console
        System.out.println(txtMaxspeed.getText());
        System.out.println(sql);
        if (!m.matches() || !m2.matches() || !m3.matches() || !m4.matches() || !m5.matches() || !m6.matches() || !m7.matches()) {
            JOptionPane.showMessageDialog(this, Phases.INVALID_FORMAT, Phases.ERROR_MESSAGE, JOptionPane.ERROR_MESSAGE);
        } else if (txtCongsuatmax.getText().equals("") || txtDongco.getText().equals("") || txtKieudc.getText().equals("")
                || txtNhienlieu.getText().equals("") || txtHopso.getText().equals("")) {
            JOptionPane.showMessageDialog(this, Phases.ERROR_EMPTY_FIELD, Phases.ERROR_MESSAGE, JOptionPane.ERROR_MESSAGE);
        } else {
            String[] data = {src + "\\" + new File(link[0]).getName(), src + "\\" + new File(link[1]).getName(), src + "\\" + new File(link[2]).getName(), src + "\\" + new File(link[3]).getName(), txtNamsx.getText(),
                txtDongco.getText(), txtKieudc.getText(), txtNhienlieu.getText(), txtHopso.getText(),
                txtCongsuatmax.getText(), txtMaxspeed.getText(), txtChieudai.getText(), txtChieurong.getText(),
                txtChieucao.getText(), txtTrongluong.getText(), txtSoghe.getText()};
            int rows = DBHandleData.UpdateData(sql, data);
            if (rows > 0) {
                JOptionPane.showMessageDialog(this, Phases.UPDATE_SUCCESSFULL);
            } else {
                JOptionPane.showMessageDialog(this, Phases.UPDATE_FAILURE);
            }
        }
    }//GEN-LAST:event_btnSubmitActionPerformed
    String[] link = new String[4];
    String src = "";
    private void btnSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectActionPerformed
        // TODO add your handling code here:
        lblAnh1.setText("");
        lblAnh2.setText("");
        lblAnh3.setText("");
        lblAnh4.setText("");
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setMultiSelectionEnabled(true);
        int option = fileChooser.showOpenDialog(this);
        if (option == JFileChooser.APPROVE_OPTION) {
            File f = fileChooser.getSelectedFile();
            MyImages img = new MyImages(f.getName(), f.getPath());
            link[0] = img.getPath();
            Tools.fitImageToLabel(lblAnh1, img.getPath());
            if (new File(Tools.Img(img.getPath(), 1)).exists()) {
                Tools.fitImageToLabel(lblAnh2, Tools.Img(img.getPath(), 1));
                link[1] = Tools.Img(img.getPath(), 1);
            }
            if (new File(Tools.Img(img.getPath(), 2)).exists()) {
                link[2] = Tools.Img(img.getPath(), 2);
                Tools.fitImageToLabel(lblAnh3, Tools.Img(img.getPath(), 2));
            }
            if (new File(Tools.Img(img.getPath(), 3)).exists()) {
                link[3] = Tools.Img(img.getPath(), 3);
                Tools.fitImageToLabel(lblAnh4, Tools.Img(img.getPath(), 3));
            }
        }
    }//GEN-LAST:event_btnSelectActionPerformed

    private void btnUploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadActionPerformed
        // TODO add your handling code here:
        File ff = new File("images");
        String src = ff.getAbsolutePath();
        if (link[0] == null || link[1] == null || link[2] == null || link[3] == null) {
            JOptionPane.showMessageDialog(this, Phases.UPLOAD_SELECT, Phases.ERROR_MESSAGE, JOptionPane.ERROR_MESSAGE);
        } else {
            if (Tools.CopyFileTo(link[0], src) && Tools.CopyFileTo(link[1], src)
                    && Tools.CopyFileTo(link[2], src)
                    && Tools.CopyFileTo(link[3], src)) {
                JOptionPane.showMessageDialog(this, Phases.UPDATE_SUCCESSFULL);
            } else {
                JOptionPane.showMessageDialog(this, Phases.UPLOAD_FAILURE);
            }
        }
    }//GEN-LAST:event_btnUploadActionPerformed

    private void btnSelect1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelect1ActionPerformed
        // TODO add your handling code here:
        lblAnh1.setText("");
        lblAnh2.setText("");
        lblAnh3.setText("");
        lblAnh4.setText("");
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setMultiSelectionEnabled(true);
        int option = fileChooser.showOpenDialog(this);
        if (option == JFileChooser.APPROVE_OPTION) {
            File f = fileChooser.getSelectedFile();
            MyImages img = new MyImages(f.getName(), f.getPath());
            link[1] = img.getPath();
            Tools.fitImageToLabel(lblAnh2, img.getPath());
        }
    }//GEN-LAST:event_btnSelect1ActionPerformed

    private void btnSelect2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelect2ActionPerformed
        // TODO add your handling code here:
        lblAnh1.setText("");
        lblAnh2.setText("");
        lblAnh3.setText("");
        lblAnh4.setText("");
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setMultiSelectionEnabled(true);
        int option = fileChooser.showOpenDialog(this);
        if (option == JFileChooser.APPROVE_OPTION) {
            File f = fileChooser.getSelectedFile();
            MyImages img = new MyImages(f.getName(), f.getPath());
            link[2] = img.getPath();
            Tools.fitImageToLabel(lblAnh3, img.getPath());
        }
    }//GEN-LAST:event_btnSelect2ActionPerformed

    private void btnSelect3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelect3ActionPerformed
        // TODO add your handling code here:
        lblAnh1.setText("");
        lblAnh2.setText("");
        lblAnh3.setText("");
        lblAnh4.setText("");
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setMultiSelectionEnabled(true);
        int option = fileChooser.showOpenDialog(this);
        if (option == JFileChooser.APPROVE_OPTION) {
            File f = fileChooser.getSelectedFile();
            MyImages img = new MyImages(f.getName(), f.getPath());
            link[3] = img.getPath();
            Tools.fitImageToLabel(lblAnh4, img.getPath());
        }
    }//GEN-LAST:event_btnSelect3ActionPerformed
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnRs;
    private javax.swing.JButton btnSelect;
    private javax.swing.JButton btnSelect1;
    private javax.swing.JButton btnSelect2;
    private javax.swing.JButton btnSelect3;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JButton btnUpload;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JLabel lblAnh1;
    private javax.swing.JLabel lblAnh2;
    private javax.swing.JLabel lblAnh3;
    private javax.swing.JLabel lblAnh4;
    private javax.swing.JLabel lblChieucao;
    private javax.swing.JLabel lblChieurong;
    private javax.swing.JLabel lblHopso;
    private javax.swing.JLabel lblKieudc;
    private javax.swing.JLabel lblMaxcongsuat;
    private javax.swing.JLabel lblMaxspeed;
    private javax.swing.JLabel lblNamsx;
    private javax.swing.JLabel lblNhienlieu;
    private javax.swing.JLabel lblTModel;
    private javax.swing.JLabel lblTenhang;
    private javax.swing.JLabel lblTenmodel;
    private javax.swing.JLabel lblTenxe;
    private javax.swing.JLabel lblThang;
    private javax.swing.JLabel lblTxe;
    private javax.swing.JTextField txtChieucao;
    private javax.swing.JTextField txtChieudai;
    private javax.swing.JTextField txtChieurong;
    private javax.swing.JTextField txtCongsuatmax;
    private javax.swing.JTextField txtDongco;
    private javax.swing.JTextField txtHopso;
    private javax.swing.JTextField txtKieudc;
    private javax.swing.JTextField txtMaxspeed;
    private javax.swing.JTextField txtNamsx;
    private javax.swing.JTextField txtNhienlieu;
    private javax.swing.JTextField txtSoghe;
    private javax.swing.JTextField txtTrongluong;
    // End of variables declaration//GEN-END:variables
}
