/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import data.Tools;
import db.DBInitData;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JLabel;
import javax.swing.JTable;

/**
 *
 * @author tanzil
 */
public class Report extends javax.swing.JDialog {

    /**
     * Creates new form Report
     */
    public Report(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        Tools.LookAndFeel();
        this.setLocationRelativeTo(null);
        setDate();
        get1stYear();
        get2ndYear();
    }

    public void setDate() {
        Date aDate = new Date();
        SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");
        String formattedDate = formatter.format(aDate);
        lblViewDate.setText(formattedDate);
    }

    public void get1stYear() {
        String sql = "SELECT SaleInvoice.IDSale, Customer.Fullname, Car.CarName, "
                + "UserSystem.Fullname AS Admin, PayType.PayName, SaleInvoice.SaleDate, SaleInvoice.LastDate, "
                + "SaleInvoice.Status, SaleInvoice.SellPrice, Car.Price, SaleInvoice.Pay1, SaleInvoice.Date1, "
                + "SaleInvoice.Pay2, SaleInvoice.Date2, SaleInvoice.Pay3, SaleInvoice.Date3, SaleInvoice.Pay4, "
                + "SaleInvoice.Date4, SaleInvoice.Pay5, SaleInvoice.Date5, SaleInvoice.Pay6, SaleInvoice.Date6, "
                + "SaleInvoice.Installment "
                + "FROM Car INNER JOIN SaleInvoice ON Car.IDCar = SaleInvoice.IDCar "
                + "INNER JOIN Customer ON SaleInvoice.IDCus = Customer.IDCus "
                + "INNER JOIN PayType ON SaleInvoice.IDPay = PayType.IDPay "
                + "INNER JOIN UserSystem ON SaleInvoice.IDUser = UserSystem.IDUser "
                + "WHERE DATEPART(YEAR,SaleInvoice.SaleDate) < DATEPART(YEAR,GETDATE()) AND SaleInvoice.Status = 1";
        DBInitData.initCustomer(tblyear1, sql, null);
        Tools.hideColumnFrom(tblyear1, 10);
        getProfit(tblyear1, lblTotalYear1, lblProfit1);

    }

    public void get2ndYear() {
        String sql = "SELECT SaleInvoice.IDSale, Customer.Fullname, Car.CarName, "
                + "UserSystem.Fullname AS Admin, PayType.PayName, SaleInvoice.SaleDate, SaleInvoice.LastDate, "
                + "SaleInvoice.Status, SaleInvoice.SellPrice, Car.Price, SaleInvoice.Pay1, SaleInvoice.Date1, "
                + "SaleInvoice.Pay2, SaleInvoice.Date2, SaleInvoice.Pay3, SaleInvoice.Date3, SaleInvoice.Pay4, "
                + "SaleInvoice.Date4, SaleInvoice.Pay5, SaleInvoice.Date5, SaleInvoice.Pay6, SaleInvoice.Date6, "
                + "SaleInvoice.Installment "
                + "FROM Car INNER JOIN SaleInvoice ON Car.IDCar = SaleInvoice.IDCar "
                + "INNER JOIN Customer ON SaleInvoice.IDCus = Customer.IDCus "
                + "INNER JOIN PayType ON SaleInvoice.IDPay = PayType.IDPay "
                + "INNER JOIN UserSystem ON SaleInvoice.IDUser = UserSystem.IDUser "
                + "WHERE DATEPART(YEAR,SaleInvoice.SaleDate) = DATEPART(YEAR,GETDATE()) AND SaleInvoice.Status = 1";
        DBInitData.initCustomer(tblyear2, sql, null);
        Tools.hideColumnFrom(tblyear2, 9);
        getProfit(tblyear2, lblTotalYear2, lblProfit2);
    }

    public void getProfit(JTable tbl, JLabel l1, JLabel l2) {
        Float total = 0f;
        Float t = 0f;
        for (int i = 0; i < tbl.getRowCount(); i++) {
            total += Float.parseFloat((String) tbl.getValueAt(i, 8));
            t += Float.parseFloat((String) tbl.getValueAt(i, 9));
        }
        l1.setText(Float.toString(total));
        l2.setText(Float.toString(total - t));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblViewDate = new javax.swing.JLabel();
        lbl1stYear = new javax.swing.JLabel();
        lbl1stYear1 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblyear2 = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblyear1 = new javax.swing.JTable();
        btnOK = new javax.swing.JButton();
        lbl1stYear2 = new javax.swing.JLabel();
        lblTotalYear1 = new javax.swing.JLabel();
        lblProfit1 = new javax.swing.JLabel();
        lbl1stYear5 = new javax.swing.JLabel();
        lbl1stYear3 = new javax.swing.JLabel();
        lblTotalYear2 = new javax.swing.JLabel();
        lbl1stYear6 = new javax.swing.JLabel();
        lblProfit2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Report");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Report", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 18), new java.awt.Color(204, 0, 0))); // NOI18N

        lblViewDate.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        lblViewDate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lbl1stYear.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl1stYear.setForeground(new java.awt.Color(0, 51, 153));
        lbl1stYear.setText("2nd Year");

        lbl1stYear1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl1stYear1.setForeground(new java.awt.Color(0, 51, 153));
        lbl1stYear1.setText("1st Year");

        tblyear2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane4.setViewportView(tblyear2);

        tblyear1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane5.setViewportView(tblyear1);

        btnOK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Smiley.png"))); // NOI18N
        btnOK.setText("OK");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        lbl1stYear2.setBackground(new java.awt.Color(255, 255, 255));
        lbl1stYear2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl1stYear2.setText("The Total Money:");

        lblTotalYear1.setBackground(new java.awt.Color(255, 255, 255));
        lblTotalYear1.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N

        lblProfit1.setBackground(new java.awt.Color(255, 255, 255));
        lblProfit1.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N

        lbl1stYear5.setBackground(new java.awt.Color(255, 255, 255));
        lbl1stYear5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl1stYear5.setText("Capital Profit:");

        lbl1stYear3.setBackground(new java.awt.Color(255, 255, 255));
        lbl1stYear3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl1stYear3.setText("The Total Money:");

        lblTotalYear2.setBackground(new java.awt.Color(255, 255, 255));
        lblTotalYear2.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N

        lbl1stYear6.setBackground(new java.awt.Color(255, 255, 255));
        lbl1stYear6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl1stYear6.setText("Capital Profit:");

        lblProfit2.setBackground(new java.awt.Color(255, 255, 255));
        lblProfit2.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4)
                    .addComponent(jScrollPane5)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(319, 319, 319)
                                .addComponent(lblViewDate, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lbl1stYear, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl1stYear1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbl1stYear2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblTotalYear1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl1stYear5, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblProfit1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnOK, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lbl1stYear3, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblTotalYear2, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbl1stYear6, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblProfit2, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 142, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblViewDate, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(lbl1stYear1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl1stYear5)
                    .addComponent(lblProfit1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbl1stYear2)
                        .addComponent(lblTotalYear1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35)
                .addComponent(lbl1stYear)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl1stYear6)
                    .addComponent(lblProfit2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbl1stYear3)
                        .addComponent(lblTotalYear2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(btnOK)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnOKActionPerformed
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOK;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel lbl1stYear;
    private javax.swing.JLabel lbl1stYear1;
    private javax.swing.JLabel lbl1stYear2;
    private javax.swing.JLabel lbl1stYear3;
    private javax.swing.JLabel lbl1stYear5;
    private javax.swing.JLabel lbl1stYear6;
    private javax.swing.JLabel lblProfit1;
    private javax.swing.JLabel lblProfit2;
    private javax.swing.JLabel lblTotalYear1;
    private javax.swing.JLabel lblTotalYear2;
    private javax.swing.JLabel lblViewDate;
    private javax.swing.JTable tblyear1;
    private javax.swing.JTable tblyear2;
    // End of variables declaration//GEN-END:variables
}
