/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import data.Tools;
import db.DBHandleData;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tanzil
 */
public class ViewCusDebt extends javax.swing.JDialog {

    /**
     * Creates new form ViewCusDebt
     */
    DefaultTableModel model;

    public ViewCusDebt(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        Tools.LookAndFeel();
        this.setLocationRelativeTo(null);
        String[] col = {"ID Sale", "Customer", "Vehicle", "Status", "Sale Price", "Paid", "Debt"};
        String[][] data = {};
        model = new DefaultTableModel(data, col);
        tblView.setModel(model);
        viewData();
    }

    public void viewData() {
        Date aDate = new Date();
        SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");
        String formattedDate = formatter.format(aDate);
        lblViewDate.setText(formattedDate);
        String sql = " SELECT SaleInvoice.IDSale, Customer.Fullname, Car.CarName,  "
                + "CASE SaleInvoice.Status WHEN 0 THEN 'NOT FINISH' END AS STATUS, "
                + "SaleInvoice.SellPrice, SaleInvoice.Installment, SaleInvoice.Pay1, SaleInvoice.Pay2, "
                + "SaleInvoice.Pay3, SaleInvoice.Pay4,  SaleInvoice.Pay5, SaleInvoice.Pay6 "
                + "FROM Car INNER JOIN SaleInvoice ON Car.IDCar = SaleInvoice.IDCar "
                + "INNER JOIN Customer ON SaleInvoice.IDCus = Customer.IDCus "
                + "WHERE SaleInvoice.Status = 0       ";
        ResultSet rs = DBHandleData.SelectData(sql);
        try {
            Float gia = 0f, l1 = 0f, l2 = 0f, l3 = 0f, l4 = 0f, l5 = 0f, l6 = 0f;
            while (rs.next()) {
                gia = rs.getFloat(6);
                l1 = rs.getFloat(7);
                l2 = rs.getFloat(8);
                l3 = rs.getFloat(9);
                l4 = rs.getFloat(10);
                l5 = rs.getFloat(11);
                l6 = rs.getFloat(12);
                String paid = Float.toString(gia + l1 + l2 + l3 + l4 + l5 + l6);
                String debt = Float.toString(rs.getFloat(5) - (gia + l1 + l2 + l3 + l4 + l5 + l6));
                String[] d = {rs.getString(1), rs.getString(2), rs.getString(3),
                    rs.getString(4), rs.getString(5), paid, debt};
                model.addRow(d);
            }
        } catch (SQLException ex) {
            Logger.getLogger(ViewCusDebt.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblView = new javax.swing.JTable();
        lblViewDate = new javax.swing.JLabel();
        btnOK = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("View Customer's Debt");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Report Customer's Debt", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 18), new java.awt.Color(0, 0, 0))); // NOI18N

        tblView.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblView);

        lblViewDate.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        lblViewDate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        btnOK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Green Ball.png"))); // NOI18N
        btnOK.setText("OK");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(322, 322, 322)
                .addComponent(lblViewDate, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 735, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnOK, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(291, 291, 291))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(lblViewDate, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnOK)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnOKActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOK;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblViewDate;
    private javax.swing.JTable tblView;
    // End of variables declaration//GEN-END:variables
}
